/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as authSol from "./Auth.sol";
export type { authSol };
import type * as minterSol from "./minter.sol";
export type { minterSol };
import type * as minterFactorySol from "./minterFactory.sol";
export type { minterFactorySol };
