/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MyNFTFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createMyNFT" | "deployedContracts"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createMyNFT",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedContracts",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createMyNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedContracts",
    data: BytesLike
  ): Result;
}

export interface MyNFTFactory extends BaseContract {
  connect(runner?: ContractRunner | null): MyNFTFactory;
  waitForDeployment(): Promise<this>;

  interface: MyNFTFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createMyNFT: TypedContractMethod<
    [_URI: string, numTokens: BigNumberish],
    [void],
    "payable"
  >;

  deployedContracts: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createMyNFT"
  ): TypedContractMethod<
    [_URI: string, numTokens: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deployedContracts"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  filters: {};
}
