"use client"
import './globals.css'
import { ThirdwebProvider } from '@thirdweb-dev/react'
import { Inter } from 'next/font/google'
import { ContractProvider } from './Context/ContractContext'
import { Sepolia } from "@thirdweb-dev/chains";
const inter = Inter({ subsets: ['latin'] })

export const metadata ={
  title: 'Auth',
  description: 'Generated by create next app',
}

const supportedChainIds = [11155111];
const connectors = {
  injected: {},
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThirdwebProvider activeChain={Sepolia} clientId='c0f60d298831cba73c2e8dbdf4bc9015' >
      <ContractProvider>
        <body className={inter.className}>{children}</body>
      </ContractProvider>
      </ThirdwebProvider>
    </html>
  )
}

