"use client"
import './globals.css'
import type { Metadata } from 'next'
import { ThirdwebWeb3Provider } from '@3rdweb/hooks'
import { Inter } from 'next/font/google'
import { ContractProvider } from './Context/ContractContext'
import Navbar from './components/navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Auth',
  description: 'Generated by create next app',
}

const supportedChainIds = [11155111];
const connectors = {
  injected: {},
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ThirdwebWeb3Provider supportedChainIds={supportedChainIds} connectors={connectors} >
      <ContractProvider>
        <body className={inter.className}>{children}</body>
      </ContractProvider>
      </ThirdwebWeb3Provider>
    </html>
  )
}

