/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PremiumContract } from "./PremiumContract";
export * as factories from "./factories";
export { PremiumContract__factory } from "./factories/PremiumContract__factory";
