/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as authSol from "./Auth.sol";
export type { authSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export type { PremiumContract } from "./Auth.sol/PremiumContract";
export { PremiumContract__factory } from "./factories/Auth.sol/PremiumContract__factory";
export { Lock__factory } from "./factories/Lock__factory";
